blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/ndeadly/MissionControl/discussions
    about: Issues are for reporting bugs or requesting features. Please direct general support questions to the discussions section.
